My_Second_Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login_app.urls'))
]

login_app/urls.py
from django.urls import re_path as url
from django.urls import path
from login_app import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

app_name = 'login_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login_page, name='login'),
    path('user_login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='logout'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

login_app/models.py
from django.db import models
from django.contrib.auth.models import User
# usernmae, password, email
# Create your models here.

class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    facebook_id = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pic',blank=True)

    def __str__(self):
        return self.user.username

login_app/forms.py
from django import forms
from django.contrib.auth.models import User
from login_app.models import UserInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'password', 'email' )

class UserInfoForm(forms.ModelForm):
    class Meta():
        model = UserInfo
        fields = ('facebook_id', 'profile_pic')

login_app/views.py
from django.shortcuts import render
from login_app.forms import UserForm, UserInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from django.contrib.auth.models import User
from login_app.models import UserInfo
# Create your views here.

def index(request):
    diction = {'title':"Home"}
    if request.user.is_authenticated:
        current_user = request.user
        user_id = current_user.id
        user_basic_info = User.objects.get(pk = user_id)
        user_more_info = UserInfo.objects.get(user__pk = user_id) #for relational database we use (base model__pk=usier id)
        diction.update({'user_basic_info':user_basic_info, 'user_more_info':user_more_info})
        # print(current_user.username)
        # print(current_user.email)
        # print(current_user.id)
        # print(request)
    return render(request, 'login_app/index.html', context=diction)

def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        user_info_form = UserInfoForm(data=request.POST)

        if user_form.is_valid() and user_info_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            user_info = user_info_form.save(commit=False) #commt false will not update the database
            user_info.user = user

            if 'profile_pic' in request.FILES:
                user_info.profile_pic = request.FILES['profile_pic']

            user_info.save()
            registered = True
    else:
        user_form = UserForm()
        user_info_form = UserInfoForm()

    diction = {'user_form':user_form, 'user_info_form': user_info_form, 'registered':registered}
    return render(request, 'login_app/register.html', context=diction)


def login_page(request):
    return render(request, 'login_app/login.html')

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('login_app:index'))
            else:
                return HttpResponse("Account is not active!")

        else:
            return HttpResponse("Login Details are Wrong!")

    else:
        # return render(request, 'login_app/login.html', context={})
        return HttpResponseRedirect(reverse('login_app:login'))


@login_required #it checks if the user has loged in or not.
# If the user staus is login then the user_logout will call otherwise not
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('login_app:index'))

templates/login_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="utf-8">
    <title>{{title}}</title>
  </head>
  <body>
   <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

   <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
     <ul class="navbar-nav">

       <li class="nav-item active">
        <a class="nav-link" href="{% url 'login_app:index' %}">Home</a>
       </li>

       {% if user.is_authenticated %}
       <li class="nav-item">
        <a class="nav-link" href="{% url 'login_app:logout' %}">Logout</a>
       </li>
       {% else %}
       <li class="nav-item">
        <a class="nav-link" href="{% url 'login_app:register' %}">Register</a>
       </li>

       <li class="nav-item">
        <a class="nav-link" href="{% url 'login_app:login' %}">Login</a>
       </li>
       {% endif %}


     </ul>
   </nav>

   <div class="container" style="padding-top:20px">

     {% block body_block %}

     {% endblock %}
   </div>

  </body>
</html>

templates/login_app/index.html
{% extends 'login_app/base.html' %}
{% block body_block %}
<h1>I am Index page</h1>
{% if user.is_authenticated %}
<p>Hi {{user_basic_info.username}},</p>
<p>Your Email: {{user_basic_info.email}}</p>
<p><a href="{{user_more_info.facebook_id}}">Facebook Profile</a></p>
<img src="/media/{{ user_more_info.profile_pic }}" alt="" width="200px">
{% endif %}
{% endblock %}

templates/login_app/login.html
{% extends 'login_app/base.html' %}
{% block body_block %}
<h1>Please Login:</h1>
<form action="{% url 'login_app:user_login' %}" method="POST">
  <label for="username">Username:</label>
  <input class="form-control" type="text" name="username" value="" placeholder="Enter Username.." required>

  <label for="password">password:</label>
  <input class="form-control" type="password" name="password" value="" placeholder="Enter Password.." required>
  {% csrf_token %}
  <br>
  <input class="btn btn-primary btn-sm" type="submit" name="submit" value="login">
</form>
{% endblock %}

templates/login_app/register.html
{% extends 'login_app/base.html'%}
{% block body_block %}
{% if registered %}
<div class="alert alert-success">Congratulations! Registration Successfull!</div>
{%else%}
<form enctype="multipart/form-data" method="post">
  {{user_form.as_p}}
  {{user_info_form.as_p}}
  {% csrf_token %}
  <input type="submit" name="submit" value="Register">
</form>
{% endif %}

{% endblock %}